In [88]:
import numpy as np

A = np.array([[2, 1, 0],
     [5, 3, 2],
     [20, 15, 10]], dtype=np.double)

b = np.array([12, 35, 160], dtype=np.double)

def pivot(A, b, c):
    max = np.abs(A[0, 0])
    row = 0
    for x in range (len(A)):
        if(np.abs(A[x, c]) > max):
            max = np.abs(A[x, c])
            row = x 
    replaceA = np.copy(A[0])
    replaceb = np.copy(b[0])
    A[0] = A[row]
    b[0] = b[row]
    A[row] = replaceA
    b[row] = replaceb

    return A, b

def gauss(A, b):

    row = 0
    for x in range (len(A)):
        pivot(A, b, x)

        b[x] = b[x] / A[x, row]
        A[x] = A[x] / A[x, row]
    
        for y in range (x + 1, len(A)):
            L = (A[y, row] / A[x, row])
            A[y] =  A[y] - (L * A[x])
            b[y] = b[y] - (L * b[x])
        
        row += 1

    return A

def backwards(A, b):
    
    for x in range (len(A)):
        sum = 0
        for y in range (len(A)):
            sum += A[len(A) - x - 1, y] * b[y]
        length = len(A) - x - 1
        b[length] = (b[length] - sum) + b[length] 
    
    return b 

def determinante(A):
    D = 1
    for x in range (len(A)):
        D *= A[x, x]

    return D

def IT21a_ZH04_S6_Aufg2(A, b):
    A_triangle = gauss(A, b)
    return "Obere Dreiecksmatrix:", A_triangle, "Determinante: ", determinante(A_triangle), "Lösungsvektor x: ", backwards(A_triangle, b) 

IT21a_ZH04_S6_Aufg2(A, b)


('Obere Dreiecksmatrix:',
 array([[ 1.        ,  0.75      ,  0.5       ],
        [-0.        ,  1.        ,  0.66666667],
        [-0.        , -0.        ,  1.        ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([3., 6., 1.]))

Aufgabe 3

In [87]:
from numpy import double


A1 = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]], dtype=double)

b11 = np.array([6, -12, 48], dtype=double)
b12 = np.array([-5, 19, -39], dtype=double)

IT21a_ZH04_S6_Aufg2(A1, b11)
IT21a_ZH04_S6_Aufg2(A1, b12)

A2 = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]], dtype=double)

b21 = np.array([25, -24, 107], dtype=double)
b22 = np.array([5, -22, 42], dtype=double)

IT21a_ZH04_S6_Aufg2(A2, b21)
IT21a_ZH04_S6_Aufg2(A2, b22)
gauss(A2, b22)




array([[0.        , 1.        , 2.25      ],
       [1.        , 2.83333333, 0.75      ],
       [0.        , 0.        , 1.        ]])

In [83]:
A1_solve = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]])

b11_solve = np.array([6, -12, 48])
b12_solve = np.array([-5, 19, -39])

#np.linalg.solve(A1_solve, b11_solve)
#np.linalg.solve(A1_solve, b12_solve)

A2_solve = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]])

b21_solve = np.array([25, -24, 107])
b22_solve = np.array([5, -22, 42])

#np.linalg.solve(A2_solve, b21_solve)
np.linalg.solve(A2_solve, b22_solve)


array([-2.,  3., -4.])