In [102]:
import numpy as np
from numpy import float64

A = np.array([[2, 1, 0],
     [5, 3, 2],
     [20, 15, 10]], dtype=float64)

b = np.array([15, 47, 215], dtype=float64)

def pivot(A, b, c):
    max = A[c, c] 
    row = c
    for x in range (c, len(A)):
        if(np.abs(A[x, c]) > max):
            max = A[x, c]
            row = x 
    replaceA = np.copy(A[c])
    replaceb = np.copy(b[c])
    A[c] = A[row]
    b[c] = b[row]
    A[row] = replaceA
    b[row] = replaceb

    return A, b

def gauss(A, b):

    row = 0
    for x in range (len(A)):
        pivot(A, b, x)

        b[x] = b[x] / A[x, row]
        A[x] = A[x] / A[x, row]
            
        for y in range (x + 1, len(A)):
            L = (A[y, row] / A[x, row])
            A[y] =  A[y] - (L * A[x])
            b[y] = b[y] - (L * b[x])
        
        row += 1

    return A, b

def backwards(A, b):
    
    for x in range (len(A)):
        sum = 0
        for y in range (len(A)):
            if A[len(A) - x - 1, y] != 1:
                sum += A[len(A) - x - 1, y] * b[y]
            
        length = len(A) - x - 1
        if sum >= 0:
            b[length] = (b[length] - sum)
        else:
            b[length] = (b[length] + np.abs(sum))
    
    return b 

def determinante(A):
    D = 1
    for x in range (len(A)):
        D *= A[x, x]

    return D

def IT21a_ZH04_S6_Aufg2(A, b):
    solution = gauss(A, b)
    A_triangle = solution[0]
    b_new = np.copy(solution[1])
    return "Obere Dreiecksmatrix:", A_triangle, "Determinante: ", determinante(A_triangle), "Lösungsvektor x: ", backwards(A_triangle, b_new) 

IT21a_ZH04_S6_Aufg2(A, b)


('Obere Dreiecksmatrix:',
 array([[ 1.  ,  0.75,  0.5 ],
        [-0.  ,  1.  ,  2.  ],
        [ 0.  ,  0.  ,  1.  ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([4., 7., 3.]))

In [103]:
from numpy import float64

A1 = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]], dtype=float64)

b11 = np.array([6, -12, 48], dtype=float64)
IT21a_ZH04_S6_Aufg2(A1, b11)

('Obere Dreiecksmatrix:',
 array([[ 1.     , -0.3125 , -1.28125],
        [ 0.     ,  1.     ,  6.5    ],
        [-0.     , -0.     ,  1.     ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([ 6., -2.,  4.]))

In [104]:
A1 = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]], dtype=float64)

b11 = np.array([6, -12, 48], dtype=float64)

np.linalg.solve(A1, b11)

array([ 6., -2.,  4.])

In [105]:
A1 = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]], dtype=float64)

b12 = np.array([-5, 19, -39], dtype=float64)

IT21a_ZH04_S6_Aufg2(A1, b12)


('Obere Dreiecksmatrix:',
 array([[ 1.     , -0.3125 , -1.28125],
        [ 0.     ,  1.     ,  6.5    ],
        [-0.     , -0.     ,  1.     ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([ 2., -2.,  3.]))

In [106]:
A1 = np.array([[4, -1, -5],
     [-12, 4, 17],
     [32, -10, -41]], dtype=float64)

b12 = np.array([-5, 19, -39], dtype=float64)

np.linalg.solve(A1, b12)

array([ 2., -2.,  3.])

In [107]:
A2 = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]], dtype=float64)

b21 = np.array([25, -24, 107], dtype=float64)

IT21a_ZH04_S6_Aufg2(A2, b21)

('Obere Dreiecksmatrix:',
 array([[ 1.        ,  2.83333333,  0.75      ],
        [ 0.        ,  1.        ,  2.25      ],
        [-0.        , -0.        ,  1.        ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([1., 2., 3.]))

In [108]:
A2 = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]], dtype=float64)

b21 = np.array([25, -24, 107], dtype=float64)

np.linalg.solve(A2, b21)

array([1., 2., 3.])

In [109]:
A2 = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]], dtype=float64)

b22 = np.array([5, -22, 42], dtype=float64)
IT21a_ZH04_S6_Aufg2(A2, b22)

('Obere Dreiecksmatrix:',
 array([[ 1.        ,  2.83333333,  0.75      ],
        [ 0.        ,  1.        ,  2.25      ],
        [-0.        , -0.        ,  1.        ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([-2.,  3., -4.]))

In [110]:
A2 = np.array([[2, 7, 3],
     [-4, -10, 0],
     [12, 34, 9]], dtype=float64)

b22 = np.array([5, -22, 42], dtype=float64)
np.linalg.solve(A2, b22)

array([-2.,  3., -4.])

In [111]:
A3 = np.array([[-2, 5, 4],
     [-14, 38, 22],
     [6, -9, -27]], dtype=float64)

b31 = np.array([1, 40, 75], dtype=float64)
IT21a_ZH04_S6_Aufg2(A3, b31)

('Obere Dreiecksmatrix:',
 array([[ 1.        , -1.5       , -4.5       ],
        [ 0.        ,  1.        , -2.41176471],
        [-0.        , -0.        ,  1.        ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([-1.,  3., -4.]))

In [112]:
A3 = np.array([[-2, 5, 4],
     [-14, 38, 22],
     [6, -9, -27]], dtype=float64)

b31 = np.array([1, 40, 75], dtype=float64)
np.linalg.solve(A3, b31)

array([-1.,  3., -4.])

In [113]:
A3 = np.array([[-2, 5, 4],
     [-14, 38, 22],
     [6, -9, -27]], dtype=float64)

b32 = np.array([16, 82, -120], dtype=float64)
IT21a_ZH04_S6_Aufg2(A3, b32)

('Obere Dreiecksmatrix:',
 array([[ 1.        , -1.5       , -4.5       ],
        [ 0.        ,  1.        , -2.41176471],
        [-0.        , -0.        ,  1.        ]]),
 'Determinante: ',
 1.0,
 'Lösungsvektor x: ',
 array([-5., -2.,  4.]))

In [114]:
np.linalg.solve(A3, b31)
A3 = np.array([[-2, 5, 4],
               [-14, 38, 22],
               [6, -9, -27]], dtype=float64)

b32 = np.array([16, 82, -120], dtype=float64)
np.linalg.solve(A3, b32)

array([-5., -2.,  4.])