#### Aufgabe 2

In [34]:
import numpy as np
import sympy as sp

#Teilaufgabe a.)
x, y = sp.symbols('x y')

f1 = 5*x*y
f2 = x**2 * y**2 + x + 2*y
x0 = np.array([1, 2])

h = f1.subs([(x, 1), (y, 2)])
f = sp.Matrix([f1, f2])
X = sp.Matrix([x, y])

Df = f.jacobian(X)
Df0 = Df.subs([(x, 1), (y, 2)])

func1 = sp.lambdify((x, y), f)
jac = sp.lambdify((x, y), Df)

print(jac(x0[0], x0[1]))

[[10  5]
 [ 9  6]]


In [33]:
#Teilaufgabe b.)
x, y, z = sp.symbols('x y z')

f1 = sp.log(x**2 + y**2) + z**2
f2 = sp.exp(y**2+z**2) + x**2
f3 = 1 / (z**2 + x**2) + y**2

f = sp.Matrix([f1, f2, f3])
X = sp.Matrix([x, y, z])

Df = f.jacobian(X)

func = sp.lambdify([(x, y, z)], f, "numpy")
jac = sp.lambdify((x, y, z), Df, "numpy")
x0 = np.array([1, 2, 3])

#print(jac(x0)) #??? funktioniert nicht
print(jac(1, 2, 3))

[[ 4.00000000e-01  8.00000000e-01  6.00000000e+00]
 [ 2.00000000e+00  1.76965357e+06  2.65448035e+06]
 [-2.00000000e-02  4.00000000e+00 -6.00000000e-02]]


#### Aufgabe 3

In [68]:
x, y, z = sp.symbols('x y z')

f1 = x + y**2 - z**2 - 13
f2 = sp.log(y/4) + sp.exp(0.5*z - 1) - 1
f3 = (y - 3)**2 - z**3 + 7

f = sp.Matrix([f1, f2, f3])
X = sp.Matrix([x, y, z])

Df = f.jacobian(X)

func = sp.lambdify([(x, y, z)], f, "numpy")
jac = sp.lambdify((x, y, z), Df, "numpy")

$g(x)=f\begin{pmatrix} 1.5 \\ 3 \\ 2.5 \end{pmatrix} + Df\begin{pmatrix} 1.5 \\ 3 \\ 2.5 \end{pmatrix} \cdot (\overrightarrow{x}-\begin{pmatrix} 1.5 \\ 3 \\ 2.5 \end{pmatrix})$

$Df = \begin{pmatrix} 1 & 2y & -2z \\ 0 & \frac{1}{y} & \frac{1}{2}e^{\frac{1}{2}z-1} \\ 0 & 2y-6 & -3z^2 \end{pmatrix}$

In [76]:
from numpy import transpose as t

g = t(func([1.5, 3, 2.5])) + jac(1.5, 3, 2.5)@(t(np.array([x, y, z]) - np.array([1.5, 3, 2.5])))
tg = t(g)

for x in range(len(tg)):
    print(tg[x])

[6.0*y - 5.0*z - 13.75]
[0.333333333333333*y + 0.642012708343871*z - 2.60868842662372]
[38.25 - 18.75*z]
