In [9]:
import numpy as np
import sympy as sp
sp.init_printing()      # schöner Output im Jupyter Notebook.

In [10]:
x, y = sp.symbols('x y')

In [11]:
f1 = 20 - 18*x - 2*y**2
f2 = -4*y * (x - y**2)
f = sp.Matrix([f1,f2])
f

⎡           2     ⎤
⎢-18⋅x - 2⋅y  + 20⎥
⎢                 ⎥
⎢       ⎛     2⎞  ⎥
⎣  -4⋅y⋅⎝x - y ⎠  ⎦

In [12]:
Df = f.jacobian([x,y])
Df

⎡-18       -4⋅y    ⎤
⎢                  ⎥
⎢                 2⎥
⎣-4⋅y  -4⋅x + 12⋅y ⎦

In [13]:
f = sp.lambdify([([x], [y])], f, 'numpy')
Df = sp.lambdify([([x], [y])], Df, 'numpy')

In [14]:
x = np.array([[1.1],[0.9]])

In [15]:
for k in range(4):
    print(k)
    d = np.linalg.solve(Df(x), -f(x))
    print("Df(x)")
    print(Df(x))
    print("f(x)")
    print(f(x))
    print("Delta")
    print(d)
    x += d
    print(x)
    print("Norm ||f(x)||2")
    print(np.linalg.norm(f(x), 2))
    print("Norm ||Delta||2")
    print(np.linalg.norm(d, 2))
    print("\n")

0
Df(x)
[[-18.    -3.6 ]
 [ -3.6    5.32]]
f(x)
[[-1.42 ]
 [-1.044]]
Delta
[[-0.10405445]
 [ 0.12582781]]
[[0.99594555]
 [1.02582781]]
Norm ||f(x)||2
0.23349016523989502
Norm ||Delta||2
0.1632788040724395


1
Df(x)
[[-18.          -4.10331126]
 [ -4.10331126   8.64409027]]
f(x)
[[-0.03166528]
 [ 0.23133302]]
Delta
[[ 0.00391759]
 [-0.02490232]]
[[0.99986314]
 [1.00092549]]
Norm ||f(x)||2
0.008058180551403837
Norm ||Delta||2
0.02520859288823091


2
Df(x)
[[-18.          -4.00370197]
 [ -4.00370197   8.02276954]]
f(x)
[[-0.00124025]
 [ 0.00796216]]
Delta
[[ 0.00013667]
 [-0.00092424]]
[[0.99999982]
 [1.00000125]]
Norm ||f(x)||2
1.0896993694956447e-05
Norm ||Delta||2
0.0009342905421780229


3
Df(x)
[[-18.          -4.00000501]
 [ -4.00000501   8.00003082]]
f(x)
[[-1.70843816e-06]
 [ 1.07622354e-05]]
Delta
[[ 1.83633302e-07]
 [-1.25345783e-06]]
[[1.]
 [1.]]
Norm ||f(x)||2
2.0021809739688766e-11
Norm ||Delta||2
1.2668376847068327e-06


