In [47]:
import numpy as np
import sympy as sp
sp.init_printing()      # schöner Output im Jupyter Notebook.

x, y, z = sp.symbols('x y z')

f1 = x + y**2 - z**3 - 13
f2 = sp.log(y/4) + sp.exp(0.5 * z - 1) - 1
f3 = (y - 3)**2 - z**3 + 7

f = sp.Matrix([f1, f2, f3])
f

⎡        2    3         ⎤
⎢   x + y  - z  - 13    ⎥
⎢                       ⎥
⎢ 0.5⋅z - 1      ⎛y⎞    ⎥
⎢ℯ          + log⎜─⎟ - 1⎥
⎢                ⎝4⎠    ⎥
⎢                       ⎥
⎢     3          2      ⎥
⎣  - z  + (y - 3)  + 7  ⎦

In [48]:
Df = f.jacobian([x, y, z])
Df

⎡                    2     ⎤
⎢1    2⋅y        -3⋅z      ⎥
⎢                          ⎥
⎢      1          0.5⋅z - 1⎥
⎢0     ─     0.5⋅ℯ         ⎥
⎢      y                   ⎥
⎢                          ⎥
⎢                    2     ⎥
⎣0  2⋅y - 6      -3⋅z      ⎦

In [49]:

f = sp.lambdify([([x], [y], [z])], f, 'numpy')
Df = sp.lambdify([([x], [y], [z])], Df, 'numpy')

x = np.array([[1.5], [3.], [2.5]])
epsilon = 10**-5

while np.linalg.norm(f(x), 2) > epsilon:
    print(np.linalg.norm(f(x), 2))
    print(x)
    d = np.linalg.solve(Df(x), -f(x))
    x += d


print(x)

20.072525087071913
[[1.5]
 [3. ]
 [2.5]]
0.9689652129568432
[[5.61831497]
 [3.8969475 ]
 [2.04      ]]
0.0010974235080346356
[[5.00190026]
 [3.99968329]
 [1.99988306]]
[[5.00000001]
 [4.        ]
 [2.        ]]
